#!/bin/bash
if [ -L "./__ls__" ]; then
  rm "./__ls__"
fi
ln -s "/bin/ls" "./__ls__"
if [ $? -eq 0 ]; then
  echo "The symbolic link './__ls__' was successfully created."
else
  echo "The symbolic link './__ls__' could not be created."
fi
