#!/bin/bash
html_files=$(find . -name "*.html")
for html_file in $html_files; do
  if [ -f "../$html_file" ]; then
    if [ "$html_file" -nt "../$html_file" ]; then
      cp "$html_file" "../$html_file"
      echo "The file '$html_file' was copied to '../$html_file'"
    fi
  else
    # If the file doesn't exist in the parent directory, copy it
    cp "$html_file" "../"
    echo "The file '$html_file' was copied to the parent directory."
  fi
done
